version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "05:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 99
  allow:
    - dependency-type: "all"
